// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for DevenvDeveloperKeyStatus.
const (
	Issued DevenvDeveloperKeyStatus = "issued"
	Valid  DevenvDeveloperKeyStatus = "valid"
)

// Valid indicates whether the value is a known member of the DevenvDeveloperKeyStatus enum.
func (e DevenvDeveloperKeyStatus) Valid() bool {
	switch e {
	case Issued:
		return true
	case Valid:
		return true
	default:
		return false
	}
}

// Defines values for DevenvErrorCode.
const (
	DevenvErrorCodeCliCredentialRequired DevenvErrorCode = "cli_credential_required"
	DevenvErrorCodeCliUpgradeRequired    DevenvErrorCode = "cli_upgrade_required"
	DevenvErrorCodeCodeMismatch          DevenvErrorCode = "code_mismatch"
	DevenvErrorCodeCredentialScopeDenied DevenvErrorCode = "credential_scope_denied"
	DevenvErrorCodeDeveloperKeyDisabled  DevenvErrorCode = "developer_key_disabled"
	DevenvErrorCodeDevenvDisabled        DevenvErrorCode = "devenv_disabled"
	DevenvErrorCodeForbidden             DevenvErrorCode = "forbidden"
	DevenvErrorCodeInvalidRequest        DevenvErrorCode = "invalid_request"
	DevenvErrorCodeModelsUnavailable     DevenvErrorCode = "models_unavailable"
	DevenvErrorCodeNotFound              DevenvErrorCode = "not_found"
	DevenvErrorCodeNotProjectMember      DevenvErrorCode = "not_project_member"
	DevenvErrorCodeProjectAmbiguous      DevenvErrorCode = "project_ambiguous"
	DevenvErrorCodeProjectDisabled       DevenvErrorCode = "project_disabled"
	DevenvErrorCodeProjectNotFound       DevenvErrorCode = "project_not_found"
	DevenvErrorCodeProjectNotRegistered  DevenvErrorCode = "project_not_registered"
	DevenvErrorCodeRateLimited           DevenvErrorCode = "rate_limited"
)

// Valid indicates whether the value is a known member of the DevenvErrorCode enum.
func (e DevenvErrorCode) Valid() bool {
	switch e {
	case DevenvErrorCodeCliCredentialRequired:
		return true
	case DevenvErrorCodeCliUpgradeRequired:
		return true
	case DevenvErrorCodeCodeMismatch:
		return true
	case DevenvErrorCodeCredentialScopeDenied:
		return true
	case DevenvErrorCodeDeveloperKeyDisabled:
		return true
	case DevenvErrorCodeDevenvDisabled:
		return true
	case DevenvErrorCodeForbidden:
		return true
	case DevenvErrorCodeInvalidRequest:
		return true
	case DevenvErrorCodeModelsUnavailable:
		return true
	case DevenvErrorCodeNotFound:
		return true
	case DevenvErrorCodeNotProjectMember:
		return true
	case DevenvErrorCodeProjectAmbiguous:
		return true
	case DevenvErrorCodeProjectDisabled:
		return true
	case DevenvErrorCodeProjectNotFound:
		return true
	case DevenvErrorCodeProjectNotRegistered:
		return true
	case DevenvErrorCodeRateLimited:
		return true
	default:
		return false
	}
}

// Defines values for DevenvManifestMcpExposureHint.
const (
	Deferred DevenvManifestMcpExposureHint = "deferred"
	Direct   DevenvManifestMcpExposureHint = "direct"
)

// Valid indicates whether the value is a known member of the DevenvManifestMcpExposureHint enum.
func (e DevenvManifestMcpExposureHint) Valid() bool {
	switch e {
	case Deferred:
		return true
	case Direct:
		return true
	default:
		return false
	}
}

// Defines values for DevenvManifestSchemaVersion.
const (
	N1 DevenvManifestSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the DevenvManifestSchemaVersion enum.
func (e DevenvManifestSchemaVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for DevenvModelInput.
const (
	Image DevenvModelInput = "image"
	Text  DevenvModelInput = "text"
)

// Valid indicates whether the value is a known member of the DevenvModelInput enum.
func (e DevenvModelInput) Valid() bool {
	switch e {
	case Image:
		return true
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for DevenvModelKind.
const (
	Model DevenvModelKind = "model"
	Route DevenvModelKind = "route"
)

// Valid indicates whether the value is a known member of the DevenvModelKind enum.
func (e DevenvModelKind) Valid() bool {
	switch e {
	case Model:
		return true
	case Route:
		return true
	default:
		return false
	}
}

// Defines values for DevenvModelProtocols.
const (
	AnthropicMessages DevenvModelProtocols = "anthropic-messages"
	OpenaiCompletions DevenvModelProtocols = "openai-completions"
	OpenaiResponses   DevenvModelProtocols = "openai-responses"
)

// Valid indicates whether the value is a known member of the DevenvModelProtocols enum.
func (e DevenvModelProtocols) Valid() bool {
	switch e {
	case AnthropicMessages:
		return true
	case OpenaiCompletions:
		return true
	case OpenaiResponses:
		return true
	default:
		return false
	}
}

// Defines values for DevenvUpgradeEnvelopeErrorCode.
const (
	DevenvUpgradeEnvelopeErrorCodeCliUpgradeRequired DevenvUpgradeEnvelopeErrorCode = "cli_upgrade_required"
)

// Valid indicates whether the value is a known member of the DevenvUpgradeEnvelopeErrorCode enum.
func (e DevenvUpgradeEnvelopeErrorCode) Valid() bool {
	switch e {
	case DevenvUpgradeEnvelopeErrorCodeCliUpgradeRequired:
		return true
	default:
		return false
	}
}

// Defines values for DeviceAuthorizationRequestClientID.
const (
	DevCli DeviceAuthorizationRequestClientID = "dev-cli"
)

// Valid indicates whether the value is a known member of the DeviceAuthorizationRequestClientID enum.
func (e DeviceAuthorizationRequestClientID) Valid() bool {
	switch e {
	case DevCli:
		return true
	default:
		return false
	}
}

// Defines values for DeviceDecisionRequestDecision.
const (
	Approve DeviceDecisionRequestDecision = "approve"
	Deny    DeviceDecisionRequestDecision = "deny"
)

// Valid indicates whether the value is a known member of the DeviceDecisionRequestDecision enum.
func (e DeviceDecisionRequestDecision) Valid() bool {
	switch e {
	case Approve:
		return true
	case Deny:
		return true
	default:
		return false
	}
}

// Defines values for DeviceTokenRequestGrantType.
const (
	UrnIetfParamsOauthGrantTypeDeviceCode DeviceTokenRequestGrantType = "urn:ietf:params:oauth:grant-type:device_code"
)

// Valid indicates whether the value is a known member of the DeviceTokenRequestGrantType enum.
func (e DeviceTokenRequestGrantType) Valid() bool {
	switch e {
	case UrnIetfParamsOauthGrantTypeDeviceCode:
		return true
	default:
		return false
	}
}

// Defines values for DeviceTokenResponseScope.
const (
	Devenv DeviceTokenResponseScope = "devenv"
)

// Valid indicates whether the value is a known member of the DeviceTokenResponseScope enum.
func (e DeviceTokenResponseScope) Valid() bool {
	switch e {
	case Devenv:
		return true
	default:
		return false
	}
}

// Defines values for DeviceTokenResponseTokenType.
const (
	Bearer DeviceTokenResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the DeviceTokenResponseTokenType enum.
func (e DeviceTokenResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for OAuthErrorError.
const (
	OAuthErrorErrorAccessDenied         OAuthErrorError = "access_denied"
	OAuthErrorErrorAuthorizationPending OAuthErrorError = "authorization_pending"
	OAuthErrorErrorExpiredToken         OAuthErrorError = "expired_token"
	OAuthErrorErrorInvalidGrant         OAuthErrorError = "invalid_grant"
	OAuthErrorErrorInvalidRequest       OAuthErrorError = "invalid_request"
	OAuthErrorErrorServerError          OAuthErrorError = "server_error"
	OAuthErrorErrorSlowDown             OAuthErrorError = "slow_down"
	OAuthErrorErrorUnsupportedGrantType OAuthErrorError = "unsupported_grant_type"
)

// Valid indicates whether the value is a known member of the OAuthErrorError enum.
func (e OAuthErrorError) Valid() bool {
	switch e {
	case OAuthErrorErrorAccessDenied:
		return true
	case OAuthErrorErrorAuthorizationPending:
		return true
	case OAuthErrorErrorExpiredToken:
		return true
	case OAuthErrorErrorInvalidGrant:
		return true
	case OAuthErrorErrorInvalidRequest:
		return true
	case OAuthErrorErrorServerError:
		return true
	case OAuthErrorErrorSlowDown:
		return true
	case OAuthErrorErrorUnsupportedGrantType:
		return true
	default:
		return false
	}
}

// DevenvDeveloperKey defines model for DevenvDeveloperKey.
type DevenvDeveloperKey struct {
	Credential struct {
		ExpiresAt time.Time `json:"expires_at"`
		ID        string    `json:"id"`
		Prefix    string    `json:"prefix"`

		// Secret 凭证明文（adsk_dev_ 前缀；只在 status=issued 时出现，只出现这一次）
		Secret *string `json:"secret,omitempty"`
	} `json:"credential"`

	// RenewBeforeSeconds 续签窗口：凭证剩余有效期不超过它时客户端应再次调用本端点
	RenewBeforeSeconds int                      `json:"renew_before_seconds"`
	Status             DevenvDeveloperKeyStatus `json:"status"`
	VirtualKeyID       string                   `json:"virtual_key_id"`
}

// DevenvDeveloperKeyStatus defines model for DevenvDeveloperKey.Status.
type DevenvDeveloperKeyStatus string

// DevenvDeveloperKeyEnvelope defines model for DevenvDeveloperKeyEnvelope.
type DevenvDeveloperKeyEnvelope struct {
	// Code 业务码，0 表示成功
	Code *int                `json:"code,omitempty"`
	Data *DevenvDeveloperKey `json:"data,omitempty"`

	// Details 错误码约定的附加数据（只在失败时出现，形状由 error_code 决定）
	Details interface{} `json:"details,omitempty"`

	// ErrorCode 稳定的字符串错误码（只在失败时出现；客户端按它分支，不依赖 message 文案）。 devenv 端点的取值见 DevenvErrorCode。
	ErrorCode *string `json:"error_code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestID *string `json:"request_id,omitempty"`
}

// DevenvDeveloperKeyRequest defines model for DevenvDeveloperKeyRequest.
type DevenvDeveloperKeyRequest struct {
	// HaveCredentialID 本地已有的凭证 id（.aidevstack/credentials.json）
	HaveCredentialID *string `json:"have_credential_id,omitempty"`
}

// DevenvErrorCode devenv 端点失败时信封里的 error_code（稳定契约：dev-cli 按它分支；新增取值不破坏兼容，删除 / 改名破坏兼容）。 token 端点按 RFC 8628 返回 {error, error_description}，不在此列。
type DevenvErrorCode string

// DevenvErrorEnvelope devenv 的失败信封（data 恒为 null；details 形状由 error_code 决定，见各端点说明）
type DevenvErrorEnvelope struct {
	Code    int         `json:"code"`
	Data    any         `json:"data,omitempty"`
	Details interface{} `json:"details,omitempty"`

	// ErrorCode devenv 端点失败时信封里的 error_code（稳定契约：dev-cli 按它分支；新增取值不破坏兼容，删除 / 改名破坏兼容）。 token 端点按 RFC 8628 返回 {error, error_description}，不在此列。
	ErrorCode DevenvErrorCode `json:"error_code"`
	Message   string          `json:"message"`
	RequestID *string         `json:"request_id,omitempty"`
}

// DevenvManifest 与 agent 无关、不含秘密的下发清单（schema_version 只在不兼容变更时升级）
type DevenvManifest struct {
	Defaults struct {
		Model         string `json:"model"`
		SmallModel    string `json:"small_model"`
		ThinkingLevel string `json:"thinking_level"`
	} `json:"defaults"`
	Gateway struct {
		// AnthropicBaseURL 不含 /v1
		AnthropicBaseURL string `json:"anthropic_base_url"`

		// McpURL 聚合 MCP 端点（站点根 + /v1/mcp；是否配置看 mcp.enabled）
		McpURL string `json:"mcp_url"`

		// OpenaiBaseURL 含 /v1
		OpenaiBaseURL string `json:"openai_base_url"`
	} `json:"gateway"`
	Mcp struct {
		// Enabled 项目有绑定且启用、未停用的 MCP 服务器（与工具当前是否连通无关）
		Enabled bool `json:"enabled"`

		// ExposureHint 工具数 ≤ 16 为 direct，否则 deferred（pi 的 exposure）
		ExposureHint DevenvManifestMcpExposureHint `json:"exposure_hint"`

		// ServerName agent 里的服务器名（固定 aidevstack）
		ServerName string `json:"server_name"`

		// ToolCount 当前可用的授权工具数
		ToolCount int `json:"tool_count"`
	} `json:"mcp"`
	Models []DevenvModel `json:"models"`
	Policy struct {
		Agents struct {
			Claude struct {
				MinVersion string `json:"min_version"`
			} `json:"claude"`
			Pi struct {
				MinVersion string `json:"min_version"`
			} `json:"pi"`
		} `json:"agents"`
		CredentialRenewBeforeSeconds int    `json:"credential_renew_before_seconds"`
		MinCliVersion                string `json:"min_cli_version"`

		// TrustRepoAgentConfig 是否加载仓库内 agent 配置（默认否）
		TrustRepoAgentConfig bool `json:"trust_repo_agent_config"`
	} `json:"policy"`
	Project       DevenvProject               `json:"project"`
	SchemaVersion DevenvManifestSchemaVersion `json:"schema_version"`

	// Skills 项目启用且有已批准版本的技能（按名称排序）
	Skills []DevenvSkill `json:"skills"`
}

// DevenvManifestMcpExposureHint 工具数 ≤ 16 为 direct，否则 deferred（pi 的 exposure）
type DevenvManifestMcpExposureHint string

// DevenvManifestSchemaVersion defines model for DevenvManifest.SchemaVersion.
type DevenvManifestSchemaVersion int

// DevenvManifestEnvelope defines model for DevenvManifestEnvelope.
type DevenvManifestEnvelope struct {
	// Code 业务码，0 表示成功
	Code *int `json:"code,omitempty"`

	// Data 与 agent 无关、不含秘密的下发清单（schema_version 只在不兼容变更时升级）
	Data *DevenvManifest `json:"data,omitempty"`

	// Details 错误码约定的附加数据（只在失败时出现，形状由 error_code 决定）
	Details interface{} `json:"details,omitempty"`

	// ErrorCode 稳定的字符串错误码（只在失败时出现；客户端按它分支，不依赖 message 文案）。 devenv 端点的取值见 DevenvErrorCode。
	ErrorCode *string `json:"error_code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestID *string `json:"request_id,omitempty"`
}

// DevenvModel defines model for DevenvModel.
type DevenvModel struct {
	// ContextWindow 0 = 未知
	ContextWindow int `json:"context_window"`

	// Cost 每百万 token 的单价（美元）；未知定价为 null
	Cost *struct {
		CacheRead  float64 `json:"cache_read"`
		CacheWrite float64 `json:"cache_write"`
		Input      float64 `json:"input"`
		Output     float64 `json:"output"`
	} `json:"cost"`
	DisplayName string `json:"display_name"`

	// ID 客户端用名（与 /v1/models 的 id 一致）
	ID    string             `json:"id"`
	Input []DevenvModelInput `json:"input"`
	Kind  DevenvModelKind    `json:"kind"`

	// MaxOutputTokens 0 = 未知
	MaxOutputTokens int  `json:"max_output_tokens"`
	PromptCache     bool `json:"prompt_cache"`

	// Protocols 上游原生协议（按偏好排序）
	Protocols []DevenvModelProtocols `json:"protocols"`
	Provider  string                 `json:"provider"`
	Reasoning bool                   `json:"reasoning"`
}

// DevenvModelInput defines model for DevenvModel.Input.
type DevenvModelInput string

// DevenvModelKind defines model for DevenvModel.Kind.
type DevenvModelKind string

// DevenvModelProtocols defines model for DevenvModel.Protocols.
type DevenvModelProtocols string

// DevenvProject defines model for DevenvProject.
type DevenvProject struct {
	// ConsoleURL 控制台里这个项目的页面（如 https://console.example.com/app/projects/p1；需要人去控制台处理时 dev-cli 给出它）
	ConsoleURL string `json:"console_url"`
	ID         string `json:"id"`
	Name       string `json:"name"`
	TeamID     string `json:"team_id"`
	TeamName   string `json:"team_name"`
}

// DevenvResolveEnvelope defines model for DevenvResolveEnvelope.
type DevenvResolveEnvelope struct {
	// Code 业务码，0 表示成功
	Code *int                 `json:"code,omitempty"`
	Data *DevenvResolveResult `json:"data,omitempty"`

	// Details 错误码约定的附加数据（只在失败时出现，形状由 error_code 决定）
	Details interface{} `json:"details,omitempty"`

	// ErrorCode 稳定的字符串错误码（只在失败时出现；客户端按它分支，不依赖 message 文案）。 devenv 端点的取值见 DevenvErrorCode。
	ErrorCode *string `json:"error_code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestID *string `json:"request_id,omitempty"`
}

// DevenvResolveRequest defines model for DevenvResolveRequest.
type DevenvResolveRequest struct {
	// ProjectHint 上次绑定的项目 id（多个候选时消歧）
	ProjectHint *string `json:"project_hint,omitempty"`
	Remotes     []struct {
		// Name remote 名（origin / upstream …）
		Name *string `json:"name,omitempty"`
		URL  string  `json:"url"`
	} `json:"remotes"`

	// Subpath 工作目录相对仓库根的子路径（monorepo），空 = 仓库根
	Subpath *string `json:"subpath,omitempty"`
}

// DevenvResolveResult defines model for DevenvResolveResult.
type DevenvResolveResult struct {
	Matched struct {
		PathPrefix    string `json:"path_prefix"`
		Remote        string `json:"remote"`
		URLNormalized string `json:"url_normalized"`
	} `json:"matched"`
	Project DevenvProject `json:"project"`
}

// DevenvSkill 清单里的一个可下发技能版本
type DevenvSkill struct {
	// BundleURL 技能包地址（相对平台站点根，如 /api/v1/devenv/projects/p1/skills/x/1.0.0.zip）
	BundleURL string `json:"bundle_url"`

	// Digest sha256:<hex>（技能包字节的 sha256）
	Digest string `json:"digest"`
	Name   string `json:"name"`

	// Size 技能包字节数
	Size    int64  `json:"size"`
	Version string `json:"version"`
}

// DevenvUpgradeDetails defines model for DevenvUpgradeDetails.
type DevenvUpgradeDetails struct {
	CurrentVersion string `json:"current_version"`
	MinVersion     string `json:"min_version"`
	Upgrade        struct {
		Brew      string `json:"brew"`
		GoInstall string `json:"go_install"`
		URL       string `json:"url"`
	} `json:"upgrade"`
}

// DevenvUpgradeEnvelope 426 的失败信封（data 恒为 null）
type DevenvUpgradeEnvelope struct {
	// Code 业务码 10003
	Code      int                            `json:"code"`
	Data      any                            `json:"data,omitempty"`
	Details   DevenvUpgradeDetails           `json:"details"`
	ErrorCode DevenvUpgradeEnvelopeErrorCode `json:"error_code"`
	Message   string                         `json:"message"`
	RequestID *string                        `json:"request_id,omitempty"`
}

// DevenvUpgradeEnvelopeErrorCode defines model for DevenvUpgradeEnvelope.ErrorCode.
type DevenvUpgradeEnvelopeErrorCode string

// Device defines model for Device.
type Device struct {
	CreatedAt time.Time `json:"created_at"`

	// Current 发起本次请求的就是这台设备
	Current    bool       `json:"current"`
	DeviceName string     `json:"device_name"`
	ExpiresAt  *time.Time `json:"expires_at,omitempty"`
	ID         string     `json:"id"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	LastUsedIP *string    `json:"last_used_ip,omitempty"`
	Os         string     `json:"os"`

	// Prefix 凭据前缀（只作辨识）
	Prefix string `json:"prefix"`
}

// DeviceAuthorization defines model for DeviceAuthorization.
type DeviceAuthorization struct {
	// DeviceCode 只出现这一次；轮询时原样带回
	DeviceCode string `json:"device_code"`

	// ExpiresIn 秒（600）
	ExpiresIn int `json:"expires_in"`

	// Interval 轮询间隔秒数（5）
	Interval int `json:"interval"`

	// UserCode XXXX-XXXX
	UserCode                string `json:"user_code"`
	VerificationURI         string `json:"verification_uri"`
	VerificationURIComplete string `json:"verification_uri_complete"`
}

// DeviceAuthorizationEnvelope defines model for DeviceAuthorizationEnvelope.
type DeviceAuthorizationEnvelope struct {
	// Code 业务码，0 表示成功
	Code *int                 `json:"code,omitempty"`
	Data *DeviceAuthorization `json:"data,omitempty"`

	// Details 错误码约定的附加数据（只在失败时出现，形状由 error_code 决定）
	Details interface{} `json:"details,omitempty"`

	// ErrorCode 稳定的字符串错误码（只在失败时出现；客户端按它分支，不依赖 message 文案）。 devenv 端点的取值见 DevenvErrorCode。
	ErrorCode *string `json:"error_code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestID *string `json:"request_id,omitempty"`
}

// DeviceAuthorizationRequest defines model for DeviceAuthorizationRequest.
type DeviceAuthorizationRequest struct {
	Arch       *string                            `json:"arch,omitempty"`
	CliVersion *string                            `json:"cli_version,omitempty"`
	ClientID   DeviceAuthorizationRequestClientID `json:"client_id"`

	// DeviceName 设备名（展示在批准页，≤128 字符）
	DeviceName *string `json:"device_name,omitempty"`
	Os         *string `json:"os,omitempty"`
}

// DeviceAuthorizationRequestClientID defines model for DeviceAuthorizationRequest.ClientID.
type DeviceAuthorizationRequestClientID string

// DeviceDecisionRequest defines model for DeviceDecisionRequest.
type DeviceDecisionRequest struct {
	Decision DeviceDecisionRequestDecision `json:"decision"`

	// TypedCode requires_typed_code 为真时必填
	TypedCode *string `json:"typed_code,omitempty"`
	UserCode  string  `json:"user_code"`
}

// DeviceDecisionRequestDecision defines model for DeviceDecisionRequest.Decision.
type DeviceDecisionRequestDecision string

// DeviceListEnvelope defines model for DeviceListEnvelope.
type DeviceListEnvelope struct {
	// Code 业务码，0 表示成功
	Code *int      `json:"code,omitempty"`
	Data *[]Device `json:"data,omitempty"`

	// Details 错误码约定的附加数据（只在失败时出现，形状由 error_code 决定）
	Details interface{} `json:"details,omitempty"`

	// ErrorCode 稳定的字符串错误码（只在失败时出现；客户端按它分支，不依赖 message 文案）。 devenv 端点的取值见 DevenvErrorCode。
	ErrorCode *string `json:"error_code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestID *string `json:"request_id,omitempty"`
}

// DeviceTokenRequest defines model for DeviceTokenRequest.
type DeviceTokenRequest struct {
	ClientID   *string                     `json:"client_id,omitempty"`
	DeviceCode string                      `json:"device_code"`
	GrantType  DeviceTokenRequestGrantType `json:"grant_type"`
}

// DeviceTokenRequestGrantType defines model for DeviceTokenRequest.GrantType.
type DeviceTokenRequestGrantType string

// DeviceTokenResponse defines model for DeviceTokenResponse.
type DeviceTokenResponse struct {
	// AccessToken CLI 凭据明文（adsk_cli_ 前缀，只出现这一次）
	AccessToken string `json:"access_token"`

	// DeviceID 设备 id（= CLI 凭据 id）
	DeviceID string `json:"device_id"`

	// ExpiresIn 秒（7 天，绝对过期、不续期）
	ExpiresIn int                          `json:"expires_in"`
	Scope     DeviceTokenResponseScope     `json:"scope"`
	TokenType DeviceTokenResponseTokenType `json:"token_type"`
	User      struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"user"`
}

// DeviceTokenResponseScope defines model for DeviceTokenResponse.Scope.
type DeviceTokenResponseScope string

// DeviceTokenResponseTokenType defines model for DeviceTokenResponse.TokenType.
type DeviceTokenResponseTokenType string

// Envelope 统一响应外壳（data 始终存在；空列表为 []）
type Envelope struct {
	// Code 业务码，0 表示成功
	Code *int        `json:"code,omitempty"`
	Data interface{} `json:"data,omitempty"`

	// Details 错误码约定的附加数据（只在失败时出现，形状由 error_code 决定）
	Details interface{} `json:"details,omitempty"`

	// ErrorCode 稳定的字符串错误码（只在失败时出现；客户端按它分支，不依赖 message 文案）。 devenv 端点的取值见 DevenvErrorCode。
	ErrorCode *string `json:"error_code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestID *string `json:"request_id,omitempty"`
}

// OAuthError defines model for OAuthError.
type OAuthError struct {
	Error            OAuthErrorError `json:"error"`
	ErrorDescription *string         `json:"error_description,omitempty"`

	// Interval slow_down 时的新轮询间隔（秒）
	Interval *int `json:"interval,omitempty"`
}

// OAuthErrorError defines model for OAuthError.Error.
type OAuthErrorError string

// PendingDevice defines model for PendingDevice.
type PendingDevice struct {
	Arch       string    `json:"arch"`
	CliVersion string    `json:"cli_version"`
	CreatedAt  time.Time `json:"created_at"`

	// CredentialTTLDays 批准后签出的 CLI 凭据有效期（天，DEVENV_CLI_CREDENTIAL_TTL_DAYS，默认 7；不续期）
	CredentialTTLDays int       `json:"credential_ttl_days"`
	DeviceName        string    `json:"device_name"`
	ExpiresAt         time.Time `json:"expires_at"`
	Os                string    `json:"os"`

	// RequestIP 发起申请的 IP
	RequestIP string `json:"request_ip"`

	// RequiresTypedCode 批准者与发起者 IP 不同：批准时必须手输用户码
	RequiresTypedCode bool     `json:"requires_typed_code"`
	Scopes            []string `json:"scopes"`
	UserCode          string   `json:"user_code"`
}

// PendingDeviceEnvelope defines model for PendingDeviceEnvelope.
type PendingDeviceEnvelope struct {
	// Code 业务码，0 表示成功
	Code *int           `json:"code,omitempty"`
	Data *PendingDevice `json:"data,omitempty"`

	// Details 错误码约定的附加数据（只在失败时出现，形状由 error_code 决定）
	Details interface{} `json:"details,omitempty"`

	// ErrorCode 稳定的字符串错误码（只在失败时出现；客户端按它分支，不依赖 message 文案）。 devenv 端点的取值见 DevenvErrorCode。
	ErrorCode *string `json:"error_code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestID *string `json:"request_id,omitempty"`
}

// DevenvError devenv 的失败信封（data 恒为 null；details 形状由 error_code 决定，见各端点说明）
type DevenvError = DevenvErrorEnvelope

// DevenvUpgradeRequired 426 的失败信封（data 恒为 null）
type DevenvUpgradeRequired = DevenvUpgradeEnvelope

// GetDevenvManifestParams defines parameters for GetDevenvManifest.
type GetDevenvManifestParams struct {
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// GetDevenvSkillBundleParams defines parameters for GetDevenvSkillBundle.
type GetDevenvSkillBundleParams struct {
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// RequestDeviceAuthorizationJSONRequestBody defines body for RequestDeviceAuthorization for application/json ContentType.
type RequestDeviceAuthorizationJSONRequestBody = DeviceAuthorizationRequest

// DecideDeviceJSONRequestBody defines body for DecideDevice for application/json ContentType.
type DecideDeviceJSONRequestBody = DeviceDecisionRequest

// PollDeviceTokenJSONRequestBody defines body for PollDeviceToken for application/json ContentType.
type PollDeviceTokenJSONRequestBody = DeviceTokenRequest

// EnsureDeveloperKeyJSONRequestBody defines body for EnsureDeveloperKey for application/json ContentType.
type EnsureDeveloperKeyJSONRequestBody = DevenvDeveloperKeyRequest

// ResolveDevenvProjectJSONRequestBody defines body for ResolveDevenvProject for application/json ContentType.
type ResolveDevenvProjectJSONRequestBody = DevenvResolveRequest
